ifndef CONTIKI
  $(error CONTIKI not defined! You must specify where CONTIKI resides!)
endif

PIC32_MODEL=32MX470F512H

CONTIKI_PLAT_DEFS += -D __USE_TIMER__
CONTIKI_PLAT_DEFS += -D __USE_TIMER_1__ -D PIC32_TIMER_CLOCK=1
CONTIKI_PLAT_DEFS += -D __USE_TIMER_23__ -D PIC32_TIMER_RTIMER=23

CONTIKI_TARGET_SOURCEFILES = contiki-mikro-e-main.c leds-arch.c platform-init.c

CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES)

include $(CONTIKI)/cpu/pic32/Makefile.pic32
